mex -DMATLAB ...
	-v ...
    -I..\source\	...
    -I..\source\matlab	...
    ..\source\matlab\sfunction_double.c ...
    ..\source\matlab\wrapper.c ...
   	..\source\matlab\io.c ...
	..\source\matlab\adc.c ...
	..\source\matlab\pwm.c ...
	..\source\matlab\uart.c ...
	..\source\matlab\sys.c ...
	..\source\matlab\i2c.c ...
    ..\source\lib\comm.c ...
    ..\source\lib\debug.c ...
    ..\source\lib\fb.c ...
    ..\source\lib\math.c ...
    ..\source\lib\sch.c ...
	..\source\app\app.c ...
	;
