mex -DSIMULATION ...
	-v ...
    -I..\..\source\app	...
    -I..\..\source\lib	...
    -I..\..\source\hal	...
    -I..\..\source\hil\matlab	...
    ..\..\source\hil\matlab\sfunction_double.c ...
    ..\..\source\hil\matlab\wrapper.c ...
   	..\..\source\hil\matlab\io.c ...
	..\..\source\hil\matlab\sys.c ...
	..\..\source\hil\matlab\uart.c ...
	..\..\source\hil\matlab\pwm.c ...
	..\..\source\hil\matlab\adc.c ...
	..\..\source\hil\matlab\dac.c ...
	..\..\source\app\app.c ...
	..\..\source\app\ctrl.c ...
    ..\..\source\lib\sch.c ...
    ..\..\source\lib\comm.c ...
    ..\..\source\lib\error.c ...
    ..\..\source\lib\mathlib.c ...
	;
